name: music_dbt
version: 1.0.0
config-version: 2

profile: music_dbt

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

clean-targets:
  - target
  - dbt_packages

models:
  music_dbt:
    staging:
      +materialized: view
    refinement:
      +materialized: table
    marts:
      +materialized: table
